set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { Clk }]; #IO_L12P_T1_MRCC_35 Sch=clk100mhz

set_property PACKAGE_PIN M18 [get_ports Rst]
set_property IOSTANDARD LVCMOS33 [get_ports Rst]

set_property PACKAGE_PIN J15 [get_ports sw[0]]
set_property PACKAGE_PIN L16 [get_ports sw[1]]
set_property PACKAGE_PIN M13 [get_ports sw[2]]
set_property PACKAGE_PIN R15 [get_ports sw[3]]
set_property PACKAGE_PIN R17 [get_ports sw[4]]
set_property PACKAGE_PIN T18 [get_ports sw[5]]
set_property PACKAGE_PIN U18 [get_ports sw[6]]
set_property PACKAGE_PIN R13 [get_ports sw[7]]
set_property PACKAGE_PIN T8 [get_ports sw[8]]
set_property PACKAGE_PIN U8 [get_ports sw[9]]
set_property PACKAGE_PIN R16 [get_ports sw[10]]
set_property PACKAGE_PIN T13 [get_ports sw[11]]
set_property PACKAGE_PIN H6 [get_ports sw[12]]
set_property PACKAGE_PIN U12 [get_ports sw[13]]
set_property PACKAGE_PIN U11 [get_ports sw[14]]
set_property PACKAGE_PIN V10 [get_ports sw[15]]

set_property IOSTANDARD LVCMOS33 [get_ports sw[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[3]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[4]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[5]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[6]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[7]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[8]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[9]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[10]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[11]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[12]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[13]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[14]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[15]]


set_property PACKAGE_PIN T10 [get_ports abcdefg[0]]
set_property PACKAGE_PIN R10 [get_ports abcdefg[1]]
set_property PACKAGE_PIN K16 [get_ports abcdefg[2]]
set_property PACKAGE_PIN K13 [get_ports abcdefg[3]]
set_property PACKAGE_PIN P15 [get_ports abcdefg[4]]
set_property PACKAGE_PIN T11 [get_ports abcdefg[5]]
set_property PACKAGE_PIN L18 [get_ports abcdefg[6]]
set_property PACKAGE_PIN H15 [get_ports abcdefg[7]]

set_property IOSTANDARD LVCMOS33 [get_ports abcdefg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports abcdefg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports abcdefg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports abcdefg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports abcdefg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports abcdefg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports abcdefg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports abcdefg[7]]

set_property PACKAGE_PIN J17 [get_ports showPort[0]]
set_property PACKAGE_PIN J18 [get_ports showPort[1]]
set_property PACKAGE_PIN T9 [get_ports showPort[2]]
set_property PACKAGE_PIN J14 [get_ports showPort[3]]
set_property PACKAGE_PIN P14 [get_ports showPort[4]]
set_property PACKAGE_PIN T14 [get_ports showPort[5]]
set_property PACKAGE_PIN K2 [get_ports showPort[6]]
set_property PACKAGE_PIN U13 [get_ports showPort[7]]

set_property IOSTANDARD LVCMOS33 [get_ports showPort[0]]
set_property IOSTANDARD LVCMOS33 [get_ports showPort[1]]
set_property IOSTANDARD LVCMOS33 [get_ports showPort[2]]
set_property IOSTANDARD LVCMOS33 [get_ports showPort[3]]
set_property IOSTANDARD LVCMOS33 [get_ports showPort[4]]
set_property IOSTANDARD LVCMOS33 [get_ports showPort[5]]
set_property IOSTANDARD LVCMOS33 [get_ports showPort[6]]
set_property IOSTANDARD LVCMOS33 [get_ports showPort[7]]